### ISSUE TITLE
WEBSITE IS BLANK

### ISSUE THREAD

**Issue by BhuvanKumarMS** [gitname/react-gh-pages#119]
My website is blank. I have created the website using react and deployed it but it is blank can someone help me.

Code:- https://github.com/BhuvanKumarMS/AEX05
Site Link:- https://bhuvankumarms.github.io/AEX05/

**Comment by gitname** [comment]
Hi @BhuvanKumarMS, I looked at the code for your project and noticed it does not contain the code normally generated by `create-react-app`. For example, your project uses the `vite` build tool (as opposed to `webpack`, which is configured by `create-react-app`). This `react-gh-pages` tutorial is specifically about deploying a React app **created using `create-react-app`**—as opposed to an arbitrary React app (e.g. one using `vite`)—to GitHub Pages.

One thing you can do is temporarily create a new repository, follow this `react-gh-pages` tutorial there until you have successfully deployed a React app to GitHub Pages, then delete that repository and apply what you learned to your current project. One thing you may notice is that the command `npm run deploy` would run whatever `"deploy"` script is defined in your `package.json` file. When I look at the `package.json` file of your current project, I don't see a `"deploy"` script.

Closing since I don't think the project you are referring to was created by following this tutorial.
