### ISSUE TITLE
Failed to deploy after failed login

### ISSUE THREAD

**Issue by cymbiotica** [gitname/react-gh-pages#13]
I setup as the guide suggested. I got through the compile portion and then it asked me to login. I fat fingered the login and now when I try to run again it shows: 

```
> gh-pages -d build

fatal: A branch named 'gh-pages' already exists.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thought-post@0.1.0 deploy: `gh-pages -d build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thought-post@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

I cannot see the branch using git branch nor on github. How can I redo this?

**Comment by dangpro-1210** [comment]
Wow. You shouldn't use that command. I suggest that you should use gh-pages -b master -d build so that you can deploy it to the master branch (do this for a blank repo only)

**Comment by gitname** [comment]
Hi @cymbiotica, 

I don't completely understand the state of your repos (i.e. the local repo and the one on GitHub). One _drastic_ (in my opinion) way you can "start fresh" is by deleting your local project folder, [deleting the repository from GitHub](https://help.github.com/articles/deleting-a-repository), and repeating the steps listed in the guide in this repo as if it was the first time you ever did so.

You also mentioned mistyping your credentials. I wonder whether your operating system has "cached" (i.e. remembered) those incorrect credentials and will continue to prevent you from authenticating with GitHub. Have you been able to push commits to _other_ repos on GitHub since you mistyped your credentials?

**Comment by james-can** [comment]
I had the same issue, was able to solve it by uninstalling and reinstalling gh-pages
