### ISSUE TITLE
GitHub Pages shows 404 error when navigating

### ISSUE THREAD

**Issue by raviprakash11** [gitname/react-gh-pages#139]
Hi @gitname, 

I face this issue recently, "unable to navigate from one ui-component to another ui-component on gh pages". 
My testapp is successfully navigating me from one ui component to another ui component in my local, but when i deployed my app in gh page, i don't know where it is breaking, first screen is loading successfully but when its come to anyother screen it is throwing 404 error .

testapp url - https://raviprakash11.github.io/elocution/

Please help me on this !
Thanks in Advance.

**Comment by gitname** [comment]
Hi @raviprakash11, since routing is working when served by your local machine, but not when deployed to GitHub Pages, I think you are encountering the limitation of GitHub Pages described [here](https://create-react-app.dev/docs/deployment#notes-on-client-side-routing); i.e.

> GitHub Pages doesn’t support routers that use the HTML5 pushState history API under the hood (for example, React Router using browserHistory).

I recommend applying one of the two workarounds described in the following comment (which is based upon the article linked in the previous paragraph): https://github.com/gitname/react-gh-pages/issues/104#issuecomment-1203373499

**Comment by raviprakash11** [comment]
Hi @gitname , 

I appreciate for quick response. Sure, I'll check and get back to you.

Thanks.

**Comment by raviprakash11** [comment]
Hi @gitname ,

I modified my router file as per your last comment.
https://github.com/gitname/react-gh-pages/issues/104#issuecomment-1203373499

Now, it is working fine. Hence, closing this issue.

Thanks.

**Comment by gitname** [comment]
Glad it's working! Thank for following up and closing the issue.
