### ISSUE TITLE
Deployed React+Threejs  website showing blank page 

### ISSUE THREAD

**Issue by twers1** [gitname/react-gh-pages#141]
I think the problem is that he can't download node_modules because when I download these modules I have to set --legacy-peer-deps, help please

application: https://github.com/twers1/twers1.github.io

**Comment by gitname** [comment]
Hi @twers1, I looked at the `package.json` file in the repository you linked to and didn't see a `homepage` property. Also, it looked to me like you are using `vite` instead of `webpack` (apps created using `create-react-app` use `webpack` by default). Based upon those things, I think the repository you're asking about was not created by following the tutorial in this repository.

I recommend you create a new repository, following the tutorial in this repository, confirm you can deploy a React app that way, then adapt the process to the project you linked to.
