### ISSUE TITLE
How to push on Github Pages without create-react-app?

### ISSUE THREAD

**Issue by Andrea-Dispe** [gitname/react-gh-pages#51]
I created a React app without create-react-app and I manually configured Webpack. The app is working fine but how do I deploy it on Github pages?
I tried adding the react-scripts dependency and adding the default script that CRA generates, but it is not working. Is there a specific procedure I can follow to do this?

**Comment by gitname** [comment]
Hi @Andrea-Dispe,

Sorry I'm only replying now (2 years after you asked this question).

I've never created a React app without `create-react-app` (not counting some of my early experimentation with React).

I assume you could build your app, then push the "built" file tree (e.g. which may be in a folder named `build` or `dist`, for example) to some branch on GitHub; then, [configure the GitHub repository to serve the contents of that branch via GitHub Pages](https://github.com/gitname/react-gh-pages#8-configure-github-pages).

Closing because the app in question was not created by following the tutorial in this repository.
