### ISSUE TITLE
How to customize deployment commit message

### ISSUE THREAD

**Issue by IndCore** [gitname/react-gh-pages#80]
When I run `npm run deploy` , it commits to my gh-pages branch with the commit message `Updates` , which is not very descriptive and I would want to customize, how can I do that?

**Comment by gitname** [comment]
Hi @IndCore, thanks for asking. When I first saw this Issue, I didn't know how to do this. Since then, I looked into it and found a way.

As a reminder:

- In step 5, we currently add the following to `package.json`:

    ```diff
    "scripts": {
    +   "predeploy": "npm run build",
    +   "deploy": "gh-pages -d build",
        "start": "react-scripts start",
        "build": "react-scripts build",
    ```

- And, in step 7, we currently run this CLI command:

    ```shell
    $ npm run deploy
    ```

The CLI command we run in step 7 causes the `predeploy` and `deploy` scripts defined in `package.json` to run.

The `deploy` script runs a program called `gh-pages`, which can also be run directly, like this:

```shell
# In repository root...

$ ./node_modules/.bin/gh-pages --version
3.2.3

$ ./node_modules/.bin/gh-pages --help
Usage: gh-pages [options]

Options:

  # ...(this is an EXCERPT of the full output)...

  -m, --message <message>  commit message (default: "Updates")
  -n, --no-push            Commit only (with no push)
  -h, --help               output usage information
```

As shown in the `--help` output above, the `gh-pages` program supports a `-m` option, which can be used to customize the commit message.

Currently, as the tutorial is written today, the developer (e.g. you, me) isn't running `gh-pages` directly; he or she is running it via `npm run deploy`. However, he or she could run it directly instead. That would allow him or her to specify a custom commit message. Here's how that would look:

```shell
# INSTEAD of running `$ npm run deploy`, I would run...

$ npm run build
$ ./node_modules/.bin/gh-pages -d build -m "This is a custom commit message"
```

Or, as a one-liner:

```shell
# INSTEAD of running `$ npm run deploy`, I would run...

$ npm run build && ./node_modules/.bin/gh-pages -d build -m "This is a custom commit message"
```

Other than the `-m` part, those commands are the same as the ones `npm run deploy` would cause to run. Here, I am just running them directly (instead of via `npm run deploy`) so I have the opportunity to add the `-m` option followed by a custom commit message.

Thanks again for asking this question. I also was dissatisfied with the default commit message, but hadn't looked into customizing it. Seeing this Issue motivated me to do so.

**Comment by gitname** [comment]
Hi again @IndCore, I just learned something new (after posting my previous comment).

When issuing the `npm run deploy` command, the developer can append arguments to that command and npm will apply them to the `deploy` script!

In our case, we can append `-- -m "Custom commit message..."` to the `npm run deploy` command, like this (this is on a Windows machine, so the slashes are "backwards"):

![image](https://user-images.githubusercontent.com/7143133/154381617-68645857-5477-4a2a-bf77-355eeeee8923.png)

So, the procedure I recommend for specifying a custom commit message is:

In step 7, instead of running this (which -- under the hood -- causes `gh-pages` to use its default commit message of "Updates"):

```shell
$ npm run deploy
```

Run this:

```shell
$ npm run deploy -- -m "Your custom message"
```

In fact, that is what I plan to start doing, myself, when I make deployments. I also plan to update the tutorial with this tip!

**Comment by AntoHany** [comment]
not work with me?!!!
Error
Host key verification failed.
fatal: Could not read from remote repository.
