### ISSUE TITLE
Where should I store source code for user site?

### ISSUE THREAD

**Issue by valerio-pescatori** [gitname/react-gh-pages#92]
Since I'm creating a user site I added the following lines in my `package.json`: 
```diff
"scripts": {
+   "predeploy": "npm run build",
+   "deploy": "gh-pages -b master -d build",
    "start": "react-scripts start",
    "build": "react-scripts build",
```
as written in [Step 5](https://github.com/gitname/react-gh-pages#5-add-deployment-scripts-to-the-packagejson-file).

Everything works correctly but I also wanted to store the source code to GitHub. So [Step 8](https://github.com/gitname/react-gh-pages#8-optional-store-the-react-apps-source-code-on-github) suggests to commit all changes to `master`, but since this is a user site `master` branch is currently being used to store the content of the `build` folder.

Should I store the source code in a different branch or there's a better solution?

Thank you for your time.

**Comment by gitname** [comment]
Hi @valerio-pescatori,

Thanks for asking that question (and for presenting the information so clearly). 

> Should I store the source code in a different branch or there's a better solution?

I will answer your question, and then share something I just learned a few minutes ago that is going to result in a change to the tutorial (to Step 5, specifically) and may impact your next steps.

### Answer

Since you are using the `master` branch for the built app (in accordance with Step 5 as it is written today), I would recommend storing the app's source code on a different branch; e.g. `source`, `src`, `anything-but-master`, etc. 

As you pointed out (thank you!), Step 8 does not account for this situation. That is an oversight on my part.

### News

When writing the tutorial, I copied the `master` branch "requirement" from the official [Create React App documentation](https://create-react-app.dev/docs/deployment/#step-2-install-gh-pages-and-add-deploy-to-scripts-in-packagejson):

![image](https://user-images.githubusercontent.com/7143133/161398183-642e7d32-77a0-4ed7-8f18-ba3025a1b924.png)

However, I did an experiment a few minutes ago, which showed me that deploying the built app to the `master` branch is **not** required for a user site. I was able to deploy to the `gh-pages` branch, just like if I had been working on a project site.

I suspect deploying to the `master` branch was really required at some point in the past (e.g. before GitHub allowed users to choose which branch GitHub Pages would use, as shown below), but it is not required today.

![image](https://user-images.githubusercontent.com/7143133/161399748-629b3bf7-11d3-4fb1-8249-53802e118f8f.png)

For that reason, I plan to remove the note from Step 5 altogether, since (according to my experiment today) it is not necessary and its presence means Step 8 is incomplete:

![image](https://user-images.githubusercontent.com/7143133/161399956-cf68572f-273c-44e8-a510-ac459da962a5.png)

**Comment by gitname** [comment]
> I suspect deploying to the `master` branch was really required at some point in the past (e.g. before GitHub allowed users to choose which branch GitHub Pages would use, as shown below), but it is not required today.

I found this article in the GitHub blog that confirmed this suspicion to me: 
https://github.blog/changelog/2020-09-03-build-and-deploy-github-pages-from-any-branch/

For reference, I found that article via this Stack Overflow answer: 
https://stackoverflow.com/a/59575042

**Comment by gitname** [comment]
@valerio-pescatori , I have updated Step 5 so it no longer instructs the reader to deploy the built app to the `master` branch for a user site.

Here's a direct link to the updated Step 5:
https://github.com/gitname/react-gh-pages#5-add-deployment-scripts-to-the-packagejson-file

Thanks again for explaining the situation so clearly. Are you OK with me listing you as a [contributor](https://github.com/gitname/react-gh-pages#contributors) at the bottom of the README?

**Comment by valerio-pescatori** [comment]
Thank you very much for your answer! You couldn't have been clearer than that.

Yes I'm ok with being listed as contributor, thank you very much again!

And congratulations for the amazing work you've done.👌
